config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#landing'
  
  get 'about', to: 'static_pages#about'
  get 'contest', to: 'static_pages#contest'
  get 'game', to: 'static_pages#game'
  get 'practice', to: 'static_pages#practice'
  
  scope 'api' do
  	post 'update_score', to: 'turns#create'
  	get 'check', to: 'turns#check'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include SessionsHelper
	before_action :check_session, only: [:contest, :game]
	before_action :check_subscription, only: [:game]

	def landing
	end
	
	def contest
		@plan = Plan.find(1)
		@turns = Turn.all.limit(10).order(score: :desc)
		@total = Subscription.all.count * 30
		@real_value = @total * 100 / 3500
	end

	def game
	end

	def practice
	end
	
	def about
	end
	private
		def check_subscription
			if current_user.subscriptions.last.status == 0
				flash[:error] = 'Your tickets have ended.'
				redirect_to contest_path
			end
		end

		def check_session
			if !current_user
				flash[:error] = 'You must sign in first'
				redirect_to root_path 
			end
		end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<%= render 'static_pages/partials/header' %>

<header class="masthead home-container">
  <div class="container">
    <div class="row text-justify">
	<p><h1>PRIVACY POLICY</h1></p>

<br/>

<p><small>Last udated October 21, 2017</small></p>
<p>


	Martin & Clark, LLC (“we” or “us” or “our”) respects the privacy of our users (“user” or “you”). The Privacy Policy explains how we
collect, use, disclose, and safeguard your information when you visit our website aceoffs.com and our mobile application, including
any other media form, media channel, mobile website, or mobile application related or connected thereto (collectively, the “AceOff
site”). Please read this Privacy Policy carefully. IF YOU DO NOT AGREE WITH THE TERMS OF THIS PRIVACY POLICY,
PLEASE DO NOT ACCESS THE SITE.
We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will alert you about any changes
by updating the “Revised” date of this Privacy Policy. Any changes or modifications will be effective immediately upon posting the
updated Privacy Policy on the AceOff site, and you waive the right to receive specific notice of each such change or modification.
You are encouraged to periodically review this Privacy Policy to stay informed of updates. You will be deemed to have been made
aware of, will be subject to, and will be deemed to have accepted the changes in any revised Privacy Policy by your continued use
of the AceOff site after the date such revised Privacy Policy is posted.</p>
<p>
COLLECTION OF YOUR INFORMATION
We may collect information about you in a variety of ways. The information we may collect on the AceOff site includes:
Personal Data
Personally identifiable information, such as your name, shipping address, email address, and telephone number, and demographic
information, such as your age, gender, hometown, and interests, that you voluntarily give to us when you register with the AceOff
site or our mobile application, or when you choose to participate in various activities related to the AceOff site and our mobile
application, such as online chat and message boards. You are under no obligation to provide us with personal information of any
kind, however your refusal to do so may prevent you from using certain features of the AceOff site and our mobile application.
Derivative Data
Information our servers automatically collect when you access the AceOff site, such as your IP address, your browser type, your
operating system, your access times, and the pages you have viewed directly before and after accessing the AceOff site. If you
are using our mobile application, this information may also include your device name and type, your operating system, your phone
number, your country, your likes, and replies to a post, and other interactions with the application and other users via server log
files, as well as any other information you choose to provide.
Financial Data
Financial information, such as data related to your payment method (e.g. valid credit card number, card brand, expiration date)
that we may collect when you purchase, order, return, exchange, or request information about our services form the AceOff site or
our mobile application. We store only very limited, if any, financial information that we collect. Otherwise, all financial information is
stored by our payment processor, Stripe, AgeChecker.net, and you are encouraged to review their privacy policy and contact them
directly for responses to your questions.
Data From Social Networks
User information from social networking sites, such as Apple’s Game Center, Facebook, Google+, Instagram, Pinterest, Twitter,
including your name, your social network username, location, gender, birth date, email address, profile picture, and public data for
contacts, if you connect your account to such social networks. If you are using our mobile application, this information may also
include the contact information of anyone you invite to use and/or join our mobile application.
Data From Contests, Giveaways, and Surveys
Personal and other information you may provide when entering contests or giveaways and/pr responding to surveys.
Mobile Application Information
If you connect using our mobile application:
Geo­Location Information. We may request access or permission to and track location­based information from your mobile
device, either continuously or while you are using our mobile application, to provide location­based services. If you wish to
change our access or permissions, you may do so in your device’s settings.
Mobile Device Access. We may request access or permission to certain features from your mobile device, including your
mobile device’s camera, and other features. If you wish to change our access or permission ,you may do so in your device’s
settings.
Push Notifications. We may request to send you push notifications regarding your account or our Services. If you wish to optout
from receiving these types of communications, you may turn them off in your device’s settings.
</p>
<p>
USE OF YOUR INFORMATION
Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically,
we may use information collected about you via the AceOff site our mobile application to:
Administer sweepstakes and promotions
Compile anonymous statistical data and analysis for use internally or with third parties.
Deliver targeted advertising, coupons, newsletters, and promotions, and other information regarding our website and mobile
application to you.
Email you regarding your account or order.
Enable user­to­user communications.
Fulfill and manage purchases, order payments, and other transactions related to the AceOff site and our mobile application.
Increase the efficiency and operation of the AceOff site and our mobile application.
Monitor and analyze usage and trends to improve your experience with the AceOff site and our mobile application.
Prevent fraudulent transactions, monitor against theft, and protect against criminal activity.
Process payments and refunds.
Resolve disputes and troubleshoot problems.
Respond to product and customer service requests.

DISCLOSURE OF YOUR INFORMATION
We may share information we have collected about you in certain situations. Your information may be disclosed as follows:
By Law or to Protect Rights
If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential
violations of our policies, or to protect rights, property, and safety of others, we may share your information as permitted or
required by any applicable law, rule, or regulation. This includes exchanging information with other entities for fraud protection and
credit risk reduction.
</p>
</div>
</div>
</header>

<%= render 'static_pages/partials/footer' %>

app/views/static_pages/bootstrap_carousel.html.erb
    <main role="main">


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </main>

app/views/static_pages/contest.html.erb
<%= render 'static_pages/partials/header' %>

<section role="main" id="camero-container">
  <div class="container marketing" >
    <hr class="featurette-divider">

  	<div class="row featurette">
	    
	    <div class="col-md-5 text-center">
			<%= image_tag 'camero1.png', class:"featurette-image img-fluid mx-auto"%>
			<%#= render 'static_pages/partials/carousel' %>

			<div class="panel panel-default">
			<%= form_for(:payment, url: payments_path, html: { :multipart => true, id: 'user-form' }) do |f| %>
			Buy some tokens and play!
			<article>
		
			<label class="amount">
			  <span><b>Entry: $30.00</b></span>
			</label>
			</article>
			<div class="form-group ">
			<script src="https://checkout.stripe.com/checkout.js" 
			  class="stripe-button  btn-danger"
			  data-key="pk_test_dKmW1WPHNsG5WLoy2008gYaF"
			  data-description="Buy 3 tries!"
			  data-amount="<%=(@plan.price_units + @plan.price_cents).to_i%>"
			  data-locale="auto"
			  data-label='ENTER NOW'>

			 </script>	
			</div>
			<% end %>
	 		</div>
	 		<%= render 'static_pages/partials/contest_progress_bar' %>
	 		<br/>
	 		<%= link_to 'Practice game', practice_path, class: 'btn btn-xs btn-warning text-white col-md-12' %>
	 	</div>
	 	<div class="col-md-7 ">
	      <h2>Play and win a 2011 Camaro </h2>
	      <p class="text-warning"><b>Top 10 players</b></p>
	      <p class="lead">
	      	<div class="table-responsive table-hover">
	      		<table class="table table-striped table-sm">
	      			<thead>
	      				<tr>
	      					<th>#</th>
	      					<th>Player</th>
	      					<th class="text-center">Score</th>
	      				</tr>
	      			</thead>
	      				<% @turns.each_with_index do |turn,index| %>
	      				<tr style="max-height: 10px;">
	      					<td><%= index + 1 %></td>
	      					<td><%= turn.subscription.user.username.capitalize  %></td>
	      					<td class="text-center"><%= turn.score  %></td>
	      				</tr>
	      				<%end%>
	      			<tbody>
	      				
	      			</tbody>
	      		</table>
	      	</div>
	      </p>
		</div>
	</div>
<!-- 	<hr class="featurette-divider">
 -->
</section>

<!-- prizes secton -->
<%= render "static_pages/partials/prizes" %>

<!-- <hr class="featurette-divider"> -->


<!-- terms and condition jumbotron -->
<div class="container" id="termsandconditionsjumbo">
	<div class="row justify-content-center">
		<div class="col-12">
		<div class="jumbotron ">
		<div class="container">
		<h1 >TERMS AND CONDITIONS</h1>
		<%= render 'static_pages/partials/accordion' %>
		</div>
		</div>    	
		</div>
	</div>
</div>


<script type="text/javascript">
    $(document).ready(function(){
        $(".stripe-button-el span").remove();
        $("button.stripe-button-el").removeAttr('style').css({
            "display":"inline-block",
            "width":"100%",
            "padding":"15px",
            "background":"#ca5c54",
            "color":"white",
            "font-size":"1.3em" }).html("ENTER NOW");
        });
</script>


<%= render 'static_pages/partials/footer' %>

app/views/static_pages/game.html.erb
<%= render 'static_pages/partials/header' %>

<link href="/css/reset.css" rel="stylesheet">
<link href="/css/main.css" rel="stylesheet">
<div id="gamecontainer">
 <div id="gamescreen">
    <div id="sky" class="animated">
       <div id="flyarea">
          <div id="ceiling" class="animated"></div>
          <!-- This is the flying and pipe area container -->
          <div id="player" class="bird animated"></div>

          <div id="bigscore"></div>

          <div id="splash"></div>

          <div id="scoreboard">
             <div id="medal"></div>
             <div id="currentscore"></div>
             <div id="highscore"></div>
             <div id="replay"><img src="assets/replay.png" alt="replay"></div>
          </div>

          <!-- Pipes go here! -->
       </div>
    </div>
    <div id="land" class="animated"><div id="debug"></div></div>
 </div>
</div>

<div class="boundingbox" id="playerbox"></div>
<div class="boundingbox" id="pipebox"></div>

<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.transit.min.js"></script>
<script src="/js/buzz.min.js"></script>
<script src="/js/main.js"></script>
<!-- <script src="/js/app.js"></script> -->

app/views/static_pages/landing.html.erb
<%= render 'static_pages/partials/header' %>


<header class="masthead home-container">
  <div class="container">
    <div class="row">
      <div class="col-md-8" style="margin-top:50px;">
        <img class="img-fluid img-responsive" src="img/profile.png" alt="" />
        <div class="intro-text">
          <span class="name">Play games, </br> Win prizes</span>
          <hr class="style-eight">
          <span class="skills">PRIZE OFF YOUR STUFF, WHILE THE REST OF US COMPETE FOR IT.</span>
        </div>
      </div>

  	<div id="loginbox" style="margin-top:50px;" class="mainbox col-lg-4 mx-md-auto col-md-4 mx-sm-auto">
      <div class="card text-black bg-default">
          <div class="card-header">
              <div class="card-title" style='color:black'>Sign In</div>
          </div>
          <div style="padding-top:30px" class="card-body">
              <div style="display:none" id="login-alert" class="alert alert-danger col-md-12"></div>
              <%= form_for(:user, url: users_path, html: { :multipart => true, id: 'user-form' }) do |f| %>
              	
	              	<% if flash[:notification].present? && flash[:notification].count > 0 %>
		              	<span style="color: black; margin-bottom: 30px">
		              		<% flash[:notification].each do |x| %>
		              			<code><%= x %></code>
		              			<br/>
		              		<%end%>
		              		<br/>
		              	</span>
              		<%end%>
				          </span>
                  <div style="margin-bottom: 25px" class="input-group"> <span class="input-group-addon"><i class="fa fa-user"></i></span>
                      <input
                      id="login-username" type="text" class="form-control" name='user[username]' value=""
                      placeholder="Username">
                  </div>
                  <div style="margin-bottom: 25px" class="input-group"> <span class="input-group-addon"><i class="fa fa-envelope-open-o"></i></span>
                      <input
                      id="login-password" type="text" class="form-control" name='user[email]'
                      placeholder="Email">
                  </div>
                  <div style="margin-bottom: 25px" class="input-group"> <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                      <input
                      id="login-password" type="password" class="form-control" name='user[password]'
                      placeholder="Password">
                  </div>
                  <div class="input-group">
                    <div class="form-check">
                      <label style="color:#000">
                        <input id="login-terms" type="checkbox" name="terms" > agree with Terms & Conditions
                      </label>
                    </div>
                  </div>
                  <div style="margin-top:10px" class="form-group">
                      <!-- Button -->
                      <%= f.submit 'Play now', class:'btn btn-success' %>
                  </div>
                </div>
              <%end %>
          </div>
      </div>
	</div>
    </div>
    </div>
  </div>
</header>

<!-- Portfolio Grid Section -->
<section id="portfolio" class="">
  <div class="container">
    <h2 class="text-center">Open Competitions</h2>
    <hr class="style-eight">
    <div class="row">
      <div class="col-sm-4">
        <h4 class="text-center">
          Win a 2011 Camero!
        </h4>
        <p>
        You are all competing for a 2011 Chevy Camaro LT, 2-door coupe. This car has a 312 horsepower, 3.6 liter, V-6 engine. The emblems on the car have been removed to give it a Bat Mobile feel. This car has a RS package that includes blue HD headlamps with “Halo Ring” 20” inch wheels, fog lamps and blue ambient lighting on the inside. The car has backup sensors as well as a leather wrapped 3-spoke steering wheel. The inside of the car has a wide spacious feel. The car runs smooth & efficiently. 
        </p>
      </div>
      <div class="col-sm-8 ">
        <%= image_tag 'camero1.png', class:"img-fluid" %>
      </div>
    </div>
  </div>
</section>


<!-- BETA COINS SECTION -->
<section id="beta_coins" class="bg-info">
  <div class="container">
    <h2 class="text-center text-white">What are beta coins?</h2>
        <hr class="style-eight">
    <div class="row"> 
      <div class="col-12 text-white">
      <%= render 'static_pages/partials/what_are_beta_coins' %>
      </div>
    </div>
  </div>
</section>




<section class="success" id="about">
  <div class="container">
    <h2 class="text-center">Follow Us</h2>
    <hr class="style-eight">
    <div class="row-justify-content-md-center">
      <div class="col-md-auto">
        <p class="large-text-center">
          Be sure to follow us on all social media platforms
          to stay updated with daily contests until our entire 
          user-based system is available
        </p>
      </div>
    </div>
    <div class="row justify-content-center" id="social-media-main-logo">
      <div class="col-md-auto h1">
        <a href="https://www.facebook.com/AceOff/" class="white">
          <i class="fa fa-facebook" aria-hidden="true"></i>
        </a>
      </div>
      <div class="col-md-auto h1">
        <a href="https://twitter.com/AceOffs" class="white">
        <i class="fa fa-twitter" aria-hidden="true" ></i>  
        </a>
      </div>
      <div class="col-md-auto h1">
        <a href="https://www.instagram.com/aceoffs/?hl=en" class="white">
        <i class="fa fa-instagram" aria-hidden="true"></i>  
        </a>
      </div>
    </div>
  </div>
</section>






<!-- Contact Section -->
<section id="contact">
  <div class="container">
    <h2 class="text-center">Contact Us</h2>
    <hr class="style-eight">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input class="form-control" id="name" type="text" placeholder="Name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input class="form-control" id="email" type="email" placeholder="Email Address" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Phone Number</label>
              <input class="form-control" id="phone" type="tel" placeholder="Phone Number" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea class="form-control" id="message" rows="5" placeholder="Message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="form-group">
            <button type="submit" class="btn btn-success btn-lg" id="sendMessageButton">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<script>
  $('#user-form').validate({
     rules: {
         terms: "required"
      },
      messages:{
         terms: "You must "
      }
   })
</script>
<%= render 'static_pages/partials/footer' %>

app/views/static_pages/practice.html.erb
<%= render 'static_pages/partials/header' %>

<link href="/css/reset.css" rel="stylesheet">
<link href="/css/main.css" rel="stylesheet">
<div id="gamecontainer">
 <div id="gamescreen">
    <div id="sky" class="animated">
       <div id="flyarea">
          <div id="ceiling" class="animated"></div>
          <!-- This is the flying and pipe area container -->
          <div id="player" class="bird animated"></div>

          <div id="bigscore"></div>

          <div id="splash"></div>

          <div id="scoreboard">
             <div id="medal"></div>
             <div id="currentscore"></div>
             <div id="highscore"></div>
             <div id="replay"><img src="assets/replay.png" alt="replay"></div>
          </div>

          <!-- Pipes go here! -->
       </div>
    </div>
    <div id="land" class="animated"><div id="debug"></div></div>
 </div>
</div>

<div class="boundingbox" id="playerbox"></div>
<div class="boundingbox" id="pipebox"></div>

<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.transit.min.js"></script>
<script src="/js/buzz.min.js"></script>
<script src="/js/main.js"></script>
<!-- <script src="/js/app.js"></script> -->

app/views/static_pages/test.html.erb
<%= render 'static_pages/partials/coins' %>